[package]
name = "keccak-asm"
version = "0.1.0"
edition = "2021"
exclude = ["cryptogams", ".gitmodules"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1.0.0"
digest = "0.10.7"

[build-dependencies]
cc = "1.0.83"

[dev-dependencies]
hex = "0.4.3"
sha3 = "0.10.8"
